/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    programs: Program;
    hero: Hero;
    testimonials: Testimonial;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: Record<string, never>;
}

export interface User {
  id: number;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Program {
  id: number;
  title: string;
  tag: string;
  description: string;
  duration?: string | null;
  level?: ('Bazë' | 'Mesatar' | 'Avancuar') | null;
  participants?: string | null;
  accent?: string | null;
  category?:
    | ('Lidershipë & Biznes' | 'Kreativitet & Dizajn' | 'Zhvillim Personal' | 'Shitje & Shërbime' | 'Teknologji')
    | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}

export interface Hero {
  id: number;
  eyebrow?: string | null;
  title: string;
  subtitle?: string | null;
  primaryButtonText?: string | null;
  secondaryButtonText?: string | null;
  updatedAt: string;
  createdAt: string;
}

export interface Testimonial {
  id: number;
  quote: string;
  authorName: string;
  authorRole?: string | null;
  authorCompany?: string | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?: Record<string, unknown> | unknown[] | string | number | boolean | null;
  updatedAt: string;
  createdAt: string;
}

export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
